#!/bin/bash
# Install package(s) via yay, quietly and cleanly

if [ $# -eq 0 ]; then
  echo "Usage: $0 <package-name> [more-packages...]"
  exit 1
fi

yay -S --noconfirm --sudoloop --removemake --cleanmenu --cleanafter "$@"
